modLoader="javafml"

loaderVersion="[37,)"

license="Mozilla Public License 2.0"

issueTrackerURL="https://github.com/dantaeusb-mc/Zetter/issues"

[[mods]]

modId="zetter"

version="${file.jarVersion}"

displayName="Zetter"

displayURL="https://www.curseforge.com/minecraft/mc-mods/zetter"

logoFile="zetter.png"

credits='''

StuarteLitro/@ppblitto for fancy icons and Portuguese translation
diesieben07#0714 from Forge Discord for absolutely insane amount of help
gigaherz#9173 from Forge Discord for consultations about Forge and GUI

ItamarDenkberg for Hebrew translation
iSrNinja for Spanish translation
DrHesperus for Russian translation
Vakarian89 for Polish translation
cream280 for Chinese translation
OttovonBismarckderErste for German translation

Forge Discord:
Cyborgmas#0379
Amethyst#6998
Kovak#5505
Woodland Creature#3144
ChampionAsh5357#5519
Lemongradle (sciwhiz12#1286)

Examples and references:
greyminecraftcoder and all MinecraftByExample contributors
Vazkii and Quark team for opening their source code as I often used it as a reference
'''

authors="Dmitry Burlakov <dantaeusb@live.com>"

description='''
Zetter is a Minecraft mod with a simple goal of adding custom drawing interface to
create and use custom pictures in Minecraft.

Core values of this mod:
1. Encourage players to create own pixel artworks and use it in their creations;
2. Do not change vanilla gameplay in any way and try to be as much close to vanilla Minecraft feel as possible;
3. Drawing should be fun and simple;
4. Let power users to be power users as much as it doesn't overcomplicate UI;
5. Server administrators should be able to easily moderate player artworks and decide what is appropriate on their server.
'''

[[dependencies.zetter]]
    modId="forge"
    mandatory=true
    versionRange="[37,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.zetter]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1,1.18)"
    ordering="NONE"
    side="BOTH"